- hosts: all
  become: yes
  roles:
    - geerlingguy.docker
  tasks:
  - name: Install dependencies
    package:
      name: python-setuptools
      state: latest
    become: true
    ignore_errors: true
  - name: install pip pre-requisites
    pip:
      name:
        - python-setuptools
        - openshift
        - pyyaml
        - kubernetes 
