- name: Build a single node k3s cluster
  hosts: all
  vars:
    k3s_become: true
    k3s_server:
      default-local-storage-path: /opt/local-path-provisioner
      resolv-conf: /etc/resolv.conf
      write-kubeconfig: /home/opc/.kube/config
    k3s_server_manifests_templates:
      - k8s/letsencrypt.yaml
      - k8s/argocd-namespace.yaml
      - k8s/argocd-ingress.yaml
      - k8s/argocd-cmd-params-cm-patch.yml
      - k8s/pg-cluster.yaml
    k3s_server_manifests_urls:
      - url: >-
          https://github.com/cert-manager/cert-manager/releases/download/v1.12.0/cert-manager.yaml
        filename: cert-manager.yaml
      - url: >-
          https://raw.githubusercontent.com/marcoslkz/k8s-wireguard/main/wireguard-deployment.yaml
        filename: wireguard-deployment.yaml
      - url: https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.20/releases/cnpg-1.20.2.yaml
        filename: cloudnative-pg.yaml
  roles:
    - role: xanmanning.k3s
