
- name: Build a single node k3s cluster
  hosts: all
  vars:
    k3s_become: true
    k3s_server:
      default-local-storage-path: /opt/local-path-provisioner
      resolv-conf: /etc/resolv.conf
      write-kubeconfig-mode: '0644'
    # k3s_server_manifests_urls:
    #   - url: https://github.com/cert-manager/cert-manager/releases/download/v1.18.0/cert-manager.yaml
    #     filename: cert-manager.yaml
    #     filename: wireguard-deployment.yaml
    #   - url:   https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.26/releases/cnpg-1.26.0.yaml
    #     filename: cnpg.yaml

  roles:
    - role: xanmanning.k3s
  tasks:
  - name: Run kubectl command
    shell: kubectl config view --raw
    register: kubectl_output

  - name: Write kubectl output to file
    copy: content="{{ kubectl_output.stdout }}" dest=/home/opc/.kube/config

