---
- name: Install Helm Charts
  hosts: all
  user: ansible
  tasks:
    - name: Add stable chart repo
      kubernetes.core.helm_repository:
        name: external-secrets
        repo_url: https://charts.external-secrets.io
    - name: Deploy helm external-secrets
      kubernetes.core.helm:
        name: external-secrets
        chart_ref: external-secrets/external-secrets
        release_namespace: external-secrets
        create_namespace: true
