---
- name: Install Helm Charts
  hosts: all
  tasks:
    - name: Add bitnami chart repo
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: https://charts.bitnami.com/bitnami
    - name: Deploy helm argocd
      kubernetes.core.helm:
        name: argocd
        chart_ref: oci://registry-1.docker.io/bitnamicharts/argo-cd
        release_namespace: argocd
        create_namespace: true
    - name: Add external chart repo
      kubernetes.core.helm_repository:
        name: external-secrets
        repo_url: https://charts.external-secrets.io
    - name: Deploy helm external-secrets
      kubernetes.core.helm:
        name: external-secrets
        chart_ref: external-secrets/external-secrets
        release_namespace: external-secrets
        create_namespace: true
