---
- name: Install Helm Charts
  hosts: all
  tasks:
    - name: Add argocd chart repo
      kubernetes.core.helm_repository:
        name: argo
        repo_url: https://argoproj.github.io/argo-helm
    - name: Deploy helm argocd
      kubernetes.core.helm:
        name: argocd
        chart_ref: argo/argo-cd
        release_namespace: argocd
        create_namespace: true
        values:
          server: 
            extraArgs:  
              - --insecure
