---
- name: Install Helm Charts
  hosts: all
  tasks:
    - name: Add bitnami chart repo
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: https://charts.bitnami.com/bitnami
    - name: Add argocd chart repo
      kubernetes.core.helm_repository:
        name: argocd 
        repo_url: https://argoproj.github.io/argo-helm
    - name: Deploy helm argocd
      kubernetes.core.helm:
        name: argocd
        chart_ref: bitnami/argocd
        release_namespace: argocd
        create_namespace: true
    - name: Add external-secrets chart repo
      kubernetes.core.helm_repository:
        name: external-secrets
        repo_url: https://charts.external-secrets.io
    - name: Deploy helm external-secrets
      kubernetes.core.helm:
        name: external-secrets
        chart_ref: external-secrets/external-secrets
        release_namespace: external-secrets
        create_namespace: true
