---
- name: Install Helm Charts
  hosts: all
  tasks:
  - name: kubectl tls letsencrypt
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('file', ' k8s/letsencrypt.yaml') | from_yaml  }}"
  - name: kubectl argo ingress
    kubernetes.core.k8s:
      state: present
      src: ./k8s/argocd-ingress.yaml
  - name: kubectl pg cluster
    kubernetes.core.k8s:
      state: present
      src: ./k8s/pg-cluster.yaml
      apply: true
apiVersion: v1
kind: Namespace
metadata:
  name: letsencrypt 
  labels:
    app: letsencrypt
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: letsencrypt
spec:
  acme:
    email: marcos_lk@hotmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
      - http01:
          ingress:
            class: traefik
