- name: Install ingressroute
  hosts: all
  vars:
    DOMAIN_NAME: "{{ lookup('env', 'ARGO_DOMAIN_NAME')  }}"
  tasks:
  - name: Check if DOMAIN_NAME is not empty
    fail:
      msg: "DOMAIN_NAME is empty"
    when: DOMAIN_NAME == ""

  - name: Copy the letsencrypt YAML file
    template:
      src: k8s/letsencrypt.yaml
      dest: /tmp/letsencrypt.yaml
  - name: Copy the ingress YAML file
    template:
      src: k8s/argocd-ingressroute.yaml
      dest: /tmp/argocd-ingressroute.yaml
  - name: kubectl tls letsencrypt
    kubernetes.core.k8s:
      state: present
      src: /tmp/letsencrypt.yaml
      apply: true
  - name: kubectl argo ingress
    kubernetes.core.k8s:
      state: present
      src: /tmp/argocd-ingressroute.yaml
      apply: true
