- name: Install Helm Charts
  hosts: all
  tasks:
  - name: Clone the GitHub repository marcoslkz/ansible-k3s-install
    ansible.builtin.git:
      repo: https://github.com/marcoslkz/ansible-k3s-install.git
      dest: /tmp/k3s
      clone: yes
      update: yes
  - name: kubectl tls letsencrypt
    kubernetes.core.k8s:
      state: present
      src: /tmp/k3s/k8s/letsencrypt.yaml
      apply: true
  - name: kubectl argo ingress
    kubernetes.core.k8s:
      state: present
      src: /tmp/k3s/k8s/argocd-ingressroute.yaml
      apply: true
