---
- name: Install Helm Charts
  hosts: all
  tasks:
  - name: Copy script collect_audit.sh
    ansible.builtin.copy: 
      src: k8s 
      dest: ~/ 
  - name: kubectl tls letsencrypt
    kubernetes.core.k8s:
      state: present
      definition: ~/k8s/letsencrypt.yaml
  - name: kubectl argo ingress
    kubernetes.core.k8s:
      state: present
      src: ~/k8s/argocd-ingress.yaml
  - name: kubectl pg cluster
    kubernetes.core.k8s:
      state: present
      src: ~/k8s/pg-cluster.yaml
      apply: true
