- name: Install Helm Charts
  hosts: all
  tasks:
  - name: kubectl tls letsencrypt
    kubernetes.core.k8s:
      state: present
      src: ./k8s/letsencrypt.yaml
      apply: true
  - name: kubectl argo ingress
    kubernetes.core.k8s:
      state: present
      src: ./k8s/argocd-ingressroute.yaml
      apply: true
