- name: Install ingressroute
  hosts: all
  tasks:
  - name: Copy the ingress YAML file
    template:
      src: k8s/adminer.yaml
      dest: /tmp/adminer.yaml
  - name: Copy the letsencrypt YAML file
    template:
      src: k8s/letsencrypt.yaml
      dest: /tmp/letsencrypt.yaml
  - name: kubectl tls letsencrypt
    kubernetes.core.k8s:
      state: present
      src: /tmp/letsencrypt.yaml
      apply: true
  - name: kubectl adminer ingress
    kubernetes.core.k8s:
      state: present
      src: /tmp/adminer.yaml
      apply: true
      

