- name: Install ingressroute
  hosts: all
  tasks:
  - name: Copy the ingress YAML file
    template:
      src: k8s/adminer.yaml
      dest: /tmp/adminer.yaml
  - name: Copy the letsencrypt YAML file
    template:
      src: k8s/letsencrypt.yaml
      dest: /tmp/letsencrypt.yaml
  - name: kubectl tls letsencrypt
    kubernetes.core.k8s:
      state: present
      src: /tmp/letsencrypt.yaml
      apply: true
  - name: kubectl install cnpg
    kubernetes.core.k8s:
      state: present
      src: https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.26/releases/cnpg-1.26.0.yaml
      apply: true
  - name: kubectl install sealed
    kubernetes.core.k8s:
      state: present
      src: https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.30.0/controller.yaml
      apply: true
      
      
      

