- name: Install Helm Charts
  hosts: all
  vars:
    - ARGO_DOMAIN_NAME: "{{ lookup('env', 'ARGO_DOMAIN_NAME')  }}"
  tasks:
  - name: Copy the letsencrypt YAML file
    template:
      src: k8s/letsencrypt.yaml
      dest: /tmp/letsencrypt.yaml
  - name: Copy the ingress YAML file
    template:
      src: k8s/argocd-ingressroute.yaml
      dest: /tmp/argocd-ingressroute.yaml
  - name: kubectl tls letsencrypt
    kubernetes.core.k8s:
      state: present
      src: /tmp/letsencrypt.yaml
      apply: true
  - name: kubectl argo ingress
    kubernetes.core.k8s:
      state: present
      src: /tmp/argocd-ingressroute.yaml
      apply: true
