---
- name: Install Helm Charts
  hosts: all
  tasks:
  - name: install pre-requisites
    pip:
      name:
        - openshift
        - pyyaml
        - kubernetes 
  - name: kubectl tls letsencrypt
    kubernetes.core.k8s:
      state: present
      src: k8s/letsencrypt.yaml
  - name: kubectl argo ingress
    kubernetes.core.k8s:
      state: present
      src: k8s/argocd-ingress.yaml
  - name: kubectl pg cluster
    kubernetes.core.k8s:
      state: present
      src: k8s/pg-cluster.yaml
