---
- hosts: all
  gather_facts: yes
  tasks:
  - name: Upgrade all packages
    ansible.builtin.dnf:
      name: "*"
      state: latest
    become: true
  - name: Install dependencies
    ansible.builtin.dnf:
      name: 
        - python3-setuptools
    become: true
#- import_playbook: 01-docker.yaml
#- import_playbook: 02-actions.yaml
#- import_playbook: 03-k3s.yaml
#- import_playbook: 04-helm.yaml
- import_playbook: 05-path.yaml
