---
collections:
  - name: kubernetes.core
roles:
  # Install a collection from Ansible Galaxy.
  - name: xanmanning.k3s
  - name: geerlingguy.docker 
  - name: monolithprojects.github_actions_runner
  

