---
collections:
  - name: kubernetes.core
    version: > 12.0.0
roles:
  # Install a collection from Ansible Galaxy.
  - name: xanmanning.k3s
  - name: geerlingguy.docker 
  - name: monolithprojects.github_actions_runner
  

