---
collections:
  - name: kubernetes.core.helm_repository
  - name: kubernetes.core.k8s
roles:
  # Install a collection from Ansible Galaxy.
  - name: xanmanning.k3s
  - name: geerlingguy.docker 
  - name: monolithprojects.github_actions_runner
  

