apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db
  namespace: cnpg-system
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised

  storage:
    size: 8Gi

  backup:
    retentionPolicy: "7d"  # Keep backups for 7 days

  imageName: ghcr.io/cloudnative-pg/postgresql:17

  superuserSecret:
    name: db-superuser

  postgresql:
    parameters:
      max_connections: "500"
      shared_buffers: "32MB"
      effective_cache_size: "96MB"
      maintenance_work_mem: "8MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "983kB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "300"
      work_mem: "81kB"
      huge_pages: "off"
      max_wal_size: "1GB"

  bootstrap:
    initdb:
      database: db
      owner: db
      secret:
        name: db-app-access

  #backup:
  #  volume:
  #    size: 2Gi
  #    storageClass: standard