apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adminer
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: https://github.com/marcoslkz/ansible-k3s-install.git
    path: apps/adminer/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: adminer
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true