apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: domain-tls
  namespace: kube-system
spec:
  secretName: domain-tls
  dnsNames:
    - "cloudomega.sytes.net"  
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer