apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg 
  namespace: argocd
spec:
  project: default 
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: cloudnative-pg
    targetRevision: "0.24.0"
    helm:
      values: |
        controllerManager:
           replicas: 2 # Exemplo: Aumentar o número de réplicas do operador
        instances: 3
        primaryUpdateStrategy: unsupervised
        storage:
          size: 8Gipwd  
  destination:
    server: https://kubernetes.default.svc 
    namespace: pgsql 
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 
    syncOptions:
      - CreateNamespace=true 