apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg 
  namespace: argocd
spec:
  project: default 
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: cloudnative-pg
    targetRevision: "0.24.0"
    helm:
      values: |
        instances: 3
        primaryUpdateStrategy: unsupervised
        storage:
          size: 8Gi
        monitoring:
          enablePodMonitor: true
  destination:
    server: https://kubernetes.default.svc 
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true