apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-conf
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: https://github.com/marcoslkz/ansible-k3s-install.git
    path: apps/keycloak/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default

  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: keycloak
    targetRevision: "24.9.0"
    helm:
      valuesObject:
        ingress:
          enabled: true
          ingressClassName: traefik
          hostname: cloudomega.sytes.net
          pathType: Prefix
          tls: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
    
        adminIngress:
          enabled: true
          ingressClassName: traefik
          hostname: portal-cloudomega.sytes.net
          tls: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
    
        ingressProxy:
          # Define que o chart adaptera URLs e cabeçalhos via Traefik
          enable: true
    
        defaultInitContainers:
          prepareWriteDirs:
            enabled: false
        
        auth:
          adminUser: super
          adminPassword: "change-me!!!"

        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: 2000m
            memory: 4Gi

        postgresql:
          enabled: false
    
        externalDatabase:
          existingSecret: db-app-access
          existingSecretDatabaseKey: database
          existingSecretHostKey: host
          existingSecretUserKey: username
          existingSecretPasswordKey: password
          
        proxy: edge
        proxyHeaders: xforwarded


  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    
    
