apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: keycloak
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: "letsencrypt-prod" 
    #traefik.ingress.kubernetes.io/router.middlewares: secure-headers@file
spec:
  ingressClassName: traefik
  rules:
    - host: auth-cloudomega.sytes.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
  tls:
    - hosts:
        - auth-cloudomega.sytes.net
      #secretName: domain-tls