apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak
  namespace: keycloak
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`auth-cloudomega.sytes.net`)
      kind: Rule
      services:
        - name: keycloak
          port: 8080
  tls:
    certResolver: letsencrypt-prod
    
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: your-ingressroute-name
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`example.com`)
      kind: Rule
      services:
        - name: your-service-name
          port: your-service-port
  tls:
    secretName: your-secret-name
...
