---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak
  namespace: keycloak
spec:
  encryptedData:
    KCADM: AgBbe3SwAO5Fd4VrnFxmc4jSoWaJmTjJ1g7CX3kH8li6Ya0ZS6Yl6cPSqGJUfR+7hckQAJVKpjx1CVGki2s2hmjv7Rxw3NnQCfhopocbuq7bFVUTdgus+NDn7k1KjCYvx2trLRlt88BSAbyHv+A8Wr6H660+Sgi/BgR0ky6DHefJMKZSTk+9jNROvNHFRfX/ZHLlyDK8fSHUHJLa2fgjsJIZ3MpDU8QIYDm2PG78pSXmExK1BBIhtcJgZLhL4qJ++IYbmzVrnVqBP6wLlicBK5SfsY9lOGyFzEeMH3H8SWJQBlEQao8i/Nx8nI8ObG+tjymYcbDaNcytWqa9nZ81U8xAzbBgfxNQ4QOOS+7SPzalSe+awmXo5iG4jYNh6Arx+DV7Tg0UtPlvd/jZZNAiSAWGo5rAOh8GWLFPMyFklhar2TI/fDhEbjBAqr1lRDd5e+85Mp34kuF57kZWp2/gd9mwvEE37GVApS9iscFParmF/c5WqKweym0uA3bm+S5ujkjf4y9idH14vqB3raWMOc3MA3/WDfC6gmYg0sbzV2Aftie/6IVv0lxAPabyUIXJiRp++xdx5C2xqrbCq4LdBYLVgc2Fi+X9k1j1qK86U8Y9VCo49cjVr4vNkcX27eIK4ZZKYBCrF2l7kKWU3tcRPT2L+YUEdYn4EaYc3l5TvWByJIrlO4rrv8oqD1t7Hl8UTEzhJxnVL7b49oAc1/p6NwA=
    KCADMPASS: AgCLXydwuaOu+K4Jeov7mF5ETCJK7J3S7zR4tfNEuEpwmpP7vUzEd+4PyCUHp21u/9oUsfNdgbFZIeXksIslRa/gkj80JtmjhlAlmItxf4D1YshXxmwaFBjkp2M+GjoLwZLBBeiEjgMwVNmjFy3SVHZLGeoahz+pniXAIX9+SQdYzfzeqPULUIIIdt6pJLrpFvAy57J80+0RuXDhOnP4Xiv6VGgdvc7JUEaaHXCySJnP07pZNA8ChtfMHq6O74vENEBwTwEHZ/0RflXAbH21z06nLf4YeuOnwMOW2uHxtq11YjoRJGQ3THZ5ArMC2u6M5WdJz738NuhA3FNPM10fbEAnxEsEMUVB0XsmhlLn2dZOMuoaRGqUUv7Xpvm1MnC36zeDIQMmz3T9HVRs7s3hZTl728gcvf+Dx1ckwfFczrCwp4qdKLaCU3yTcHXIFVd0o5K045lEo/1GieTfKDrYPVGC+6DEJEQGjxv4bGa+3/qzbdaL4Y7ZTeI0OdBGOBom6xhNdGbwHDEs8BO6qzl5wu2iz3xfLV2Xa3fYW6APzCbC1oPXnZHg8e8mYbm6jHHA114n1lYBxGEFsQMdMFKAj4qYmh2rUqHFoyPNT3vxnzseWU8cO7DJ7o9Kj7lJY5I8g3E4vZh9XSFI03QUFle77d8MWqpiqZ03qbEzt7pobmW40xghBVfR2si7Nu9hlVWRgNevQoDI9QED1fReYzJva7Q4lAemLJ9SyaIzP8m57DE=
  template:
    metadata:
      creationTimestamp: null
      name: keycloak
      namespace: keycloak
