apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: oracle-vault
  namespace: argocd
spec:
  provider:
    oracle:
      vault: {{ORA_VAULT}}
      region: {{ORA_REGION}}
      principalType: InstancePrincipal
      auth:
        user: {{ORA_USER}}
        tenancy: {{ORA_TENANCY}}
        principalType: UserPrincipal
        secretRef:
          privatekey:
            name: oracle-secret
            key: privatekey
            namespace: argocd
          fingerprint:
            name: oracle-secret
            key: fingerprint
            namespace: argocd
    conditions: 
    - namespaceSelector:
        matchLabels:
          my.namespace.io/some-label: "oracle" # Only namespaces with that label will work

