apiVersion: postgresql.cnpg.io/v1
kind: BackupSchedule
metadata:
  name: db-backup-daily
  namespace: cnpg-system
spec:
  schedule: "0 2 * * *"  # 02:00 UTC
  backupOwnerReference: self
  immediate: true
  cluster:
    name: db
  retentionPolicy:
    retain: 7
    type: count