apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: oracle-vault
  namespace: argocd
spec:
  provider:
    oracleVault:
      authType: instancePrincipal 
      vaultId: ocid1.vault.oc1... 
      compartmentId: ocid1.compartment.oc1...
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: oracle-secret
  namespace: argocd
spec:
  storeRef:
    kind: ClusterSecretStore
    name: oracle-vault
  data:
  - secretKey: password 
    remoteRef:
      key: oracle-secret
  targetNamespace: argocd
  secretDescriptor:
    annotations:
      argocd.argoproj.io/sync-wave: "2"
      
      
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: ocivault
spec:
  provider:
    oracle:
      vault: {{ORA_VAULT}}
      region: {{ORA_REGION}}
      auth:
        user: {{ORA_USER}}
        tenancy: {{ORA_TENANCY}}
        secretRef:
          privatekey:
            name: oracle-secret
            key: privatekey
          fingerprint:
            name: oracle-secret
            key: fingerprint

