apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgsql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/marcoslkz/argocd-cloudnative-pg.git
    path: manifests
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: pgsql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
