apiVersion: v1
kind: Namespace
metadata:
  name: letsencrypt 
  labels:
    app: letsencrypt
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: argocd
spec:
  acme:
    email: marcos_lk@hotmail.com
    #server: https://acme-v02.api.letsencrypt.org/directory
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
      - http01:
          ingress:
            class: traefik
