apiVersion: v1
kind: Namespace
metadata:
  name: pg-cluster
  labels:
    app: pg-cluster
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster
  namespace: pg-cluster
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 19Gi
