apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner
  namespace: argocd
spec:
  replicas: 2
  template:
    spec:
      repository: marcoslkz/ansible-k3s-install
      labels:
        - k8s
