apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner
  namespace: actions-runner-system 
spec:
  replicas: 1
  template:
    spec:
      repository: marcoslkz/ansible-k3s-install
      labels:
        - k8sRun
