apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/external-secrets/kubernetes-external-secrets.git # using the official external-secrets repository[^1^][1]
    targetRevision: HEAD
    path: charts/kubernetes-external-secrets # using the Helm chart for installing external-secrets[^2^][2]
    helm:
      values: |
        secretDescriptor:
          annotations: 
            argocd.argoproj.io/sync-wave: "1"
        securityContext:
          runAsUser: 1000 
          fsGroup: 2000
  destination:
    server: https://kubernetes.default.svc
    namespace: default
