apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/external-secrets/kubernetes-external-secrets.git 
    targetRevision: HEAD
    path: charts/kubernetes-external-secrets
    helm:
      values: |
        secretDescriptor:
          annotations: 
            argocd.argoproj.io/sync-wave: "1"
        securityContext:
          runAsUser: 1000 
          fsGroup: 2000
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
