name: cd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  lint:
    if: ${{ false }}
    name: Ansible Lint 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Galaxy dependencies.
        run: ansible-galaxy install -r requirements.yaml
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        
  clean:
    #if: ${{ false }}
    environment: production
    runs-on: self-hosted 
    steps:
      - uses: AutoModality/action-clean@v1

  deploy:
    #needs: checkout
    environment: production
    #runs-on: ubuntu-latest
    runs-on: self-hosted 
    steps:
      - name: Checkout files
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            apps
            k8s
      - name: Play Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: cluster.yaml
          inventory: |
            [all]
            ${{ secrets.HOST_IP }} ansible_user=opc
          requirements: requirements.yaml
          key: ${{ secrets.ANSIBLE_KEY  }}
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
          ANSIBLE_DEPRECATION_WARNINGS: 'false'
          PERSONAL_ACCESS_TOKEN: ${{ secrets.ORA_ACCESS_TOKEN }}
