name: cd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Play Ansible Playbook
        uses: arillso/action.playbook@master
        with:
          playbook: cluster.yaml
          inventory: inventory.yaml
          galaxy_file: requirements.yaml
          private_key: ${{ secrets.ANSIBLE_KEY  }}
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
          ANSIBLE_DEPRECATION_WARNINGS: 'false'
          
