name: cd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  release:
    environment: production
    #runs-on: ubuntu-latest
    runs-on: self-hosted 
    steps:
      - name: Play Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: 03-cluster.yaml
          inventory: |
            [all]
            ${{ secrets.HOST_IP }} ansible_user=opc
          requirements: requirements.yaml
          key: ${{ secrets.ANSIBLE_KEY  }}
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
          ANSIBLE_DEPRECATION_WARNINGS: 'false'
