name: cd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    if: ${{ false }}
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
  release:
    environment: production
    #runs-on: ubuntu-latest
    runs-on: self-hosted 
    steps:
      - uses: AutoModality/action-clean@v1
      - uses: actions/checkout@v2
      - name: Play Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: cluster.yaml
          inventory: |
            [all]
            ${{ secrets.HOST_IP }} ansible_user=opc
          requirements: requirements.yaml
          key: ${{ secrets.ANSIBLE_KEY  }}
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
          ANSIBLE_DEPRECATION_WARNINGS: 'false'
