name: cd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  release:
    #environment: production
    #runs-on: ubuntu-latest
    #runs-on: k8s
    runs-on: self-hosted 
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo init
      - name: Play Ansible Playbook
        uses: arillso/action.playbook@master
        with:
          playbook: cluster.yaml
          inventory: inventory.yaml
          galaxy_file: requirements.yaml
          private_key: ${{ secrets.ANSIBLE_KEY  }}
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
          ANSIBLE_DEPRECATION_WARNINGS: 'false'
          
