apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
      additionalArguments:
        - "--entrypoints.web.address=:80"
        - "--entrypoints.websecure.address=:443"
        - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
        - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
        - "--certificatesresolvers.letsencrypt-prod.acme.email=marcos_lk@hotmail.com"
        #- "--certificatesresolvers.letsencrypt-prod.acme.storage=/data/acme.json"
        - "--certificatesresolvers.letsencrypt-prod.acme.httpchallenge.entrypoint=web"
        # Opcional: logging
        - "--log.level=INFO"
        - "--accesslog=true"
        - "--serversTransport.insecureSkipVerify=true"
      globalArguments:
        - "--global.sendanonymoususage=false"
        - "--global.checknewversion=false"
