apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
      additionalArguments:
        - "--entrypoints.web.address=:80"
        - "--entrypoints.websecure.address=:443"
        - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
        - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
        - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
        - "--entrypoints.websecure.http.tls=true"
        - "--entrypoints.websecure.http.tls.certResolver=letsencrypt-prod"
        - "--certificatesresolvers.letsencrypt-prod.acme.email=marcos_lk@hotmail.com"
        - "--certificatesresolvers.letsencrypt-prod.acme.storage=/data/acme.json"
        - "--certificatesresolvers.letsencrypt-prod.acme.httpchallenge.entrypoint=web"
        - "--api.dashboard=true"
        # Opcional: logging
        - "--log.level=INFO"
        #- "--accesslog=true"
        - "--serversTransport.insecureSkipVerify=true"
        - "--providers.kubernetescrd.ingressclass=traefik-external"
      globalArguments:
        - "--global.sendanonymoususage=false"
        - "--global.checknewversion=false"

      ports:
        web:
          port: 80
          expose:
            default: true
          exposedPort: 80
          protocol: TCP
        websecure:
          port: 443
          expose:
            default: true
          exposedPort: 443
          protocol: TCP
          tls:
            enabled: true

      rbac:
        enabled: true

      ingressRoute:
        dashboard:
          enabled: true

      persistence:
        enabled: true
        name: data
        accessMode: ReadWriteOnce
        size: 1Gi
        path: /data
  
      deployment:
        initContainers:
          - name: volume-permissions
            image: busybox:1.35
            command: ["sh", "-c", "chmod 600 /data/acme.json || true"]
            volumeMounts:
              - name: data
                mountPath: /data
                
      tlsOptions:
        default:
          minVersion: VersionTLS12
          maxVersion: VersionTLS13
          cipherSuites:
            - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
            - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
            - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
            - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
            - TLS_AES_128_GCM_SHA256         # TLS 1.3
            - TLS_AES_256_GCM_SHA384         # TLS 1.3
          curvePreferences:
            - CurveP521
            - CurveP384
