apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
      additionalArguments:
        - "--entrypoints.web.address=:80"
        - "--entrypoints.websecure.address=:443"
        - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
        - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
        - "--certificatesresolvers.letsencrypt-prod.acme.email=marcos_lk@hotmail.com"
        #- "--certificatesresolvers.letsencrypt-prod.acme.storage=/data/acme.json"
        - "--certificatesresolvers.letsencrypt-prod.acme.httpchallenge.entrypoint=web"
        - "--api.dashboard=true"
        # Opcional: logging
        - "--log.level=INFO"
        - "--accesslog=true"
        - "--serversTransport.insecureSkipVerify=true"
        - "--providers.kubernetescrd.ingressclass=traefik-external"
      globalArguments:
        - "--global.sendanonymoususage=false"
        - "--global.checknewversion=false"

      ports:
        web:
          port: 80
          expose:
            default: true
          exposedPort: 80
          protocol: TCP
        websecure:
          port: 443
          expose:
            default: true
          exposedPort: 443
          protocol: TCP
          tls:
            enabled: true

      persistence:
        enabled: true
        name: data
        accessMode: ReadWriteOnce
        size: 1Gi
        path: /data
        
      rbac:
        enabled: true
      
