apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    certResolvers:
      letsencrypt-prod:
        acme:
          email: marcos_lk@hotmail.com
          storage: /data/acme.json
          httpChallenge:
            entryPoint: web

    globalArguments:
      - "--global.sendanonymoususage=false"
      - "--global.checknewversion=false"

    additionalArguments:
      - "--serversTransport.insecureSkipVerify=true"

    rbac:
      enabled: true

  
